/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Moment,
} from './typings/moment';


export namespace Components {

  interface RunopencodeChoiceType {
    'display': number | null;
    'getValue': () => Promise<string | string[]>;
    'placeholder': string | null;
    'searchPlaceholder': string | null;
    'setValue': (value: string | string[]) => Promise<void>;
  }
  interface RunopencodeChoiceTypeAttributes extends StencilHTMLAttributes {
    'display'?: number | null;
    'onChange'?: (event: CustomEvent) => void;
    'placeholder'?: string | null;
    'searchPlaceholder'?: string | null;
  }

  interface RunopencodeDateRangeType {
    'dateFormat': string;
    'disableWeekends': boolean;
    'disabled': boolean;
    'getDateFrom': () => Promise<Date>;
    'getDateTo': () => Promise<Date>;
    'getValue': () => Promise<[Date, Date]>;
    'maxDate': Moment | String | Number | Date;
    'maxDays': number | null;
    'minDate': Moment | String | Number | Date;
    'minDays': number | null;
    'numberOfMonths': number;
    'placeholder': string;
    'readonly': boolean;
    'required': boolean;
    'setDateFrom': (from: Date) => Promise<void>;
    'setDateTo': (to: Date) => Promise<void>;
    'setValue': (from: Date, to: Date) => Promise<void>;
    'theme': string;
  }
  interface RunopencodeDateRangeTypeAttributes extends StencilHTMLAttributes {
    'dateFormat'?: string;
    'disableWeekends'?: boolean;
    'disabled'?: boolean;
    'maxDate'?: Moment | String | Number | Date;
    'maxDays'?: number | null;
    'minDate'?: Moment | String | Number | Date;
    'minDays'?: number | null;
    'numberOfMonths'?: number;
    'onChange'?: (event: CustomEvent) => void;
    'placeholder'?: string;
    'readonly'?: boolean;
    'required'?: boolean;
    'theme'?: string;
  }

  interface RunopencodeDateType {
    'dateFormat': string;
    'disableWeekends': boolean;
    'disabled': boolean;
    'getValue': () => Promise<Date>;
    'maxDate': Moment | String | Number | Date;
    'minDate': Moment | String | Number | Date;
    'placeholder': string;
    'readonly': boolean;
    'required': boolean;
    'setValue': (date: Date) => Promise<void>;
    'theme': string;
  }
  interface RunopencodeDateTypeAttributes extends StencilHTMLAttributes {
    'dateFormat'?: string;
    'disableWeekends'?: boolean;
    'disabled'?: boolean;
    'maxDate'?: Moment | String | Number | Date;
    'minDate'?: Moment | String | Number | Date;
    'onChange'?: (event: CustomEvent) => void;
    'placeholder'?: string;
    'readonly'?: boolean;
    'required'?: boolean;
    'theme'?: string;
  }

  interface RunopencodeProfilePhotoEditor {
    /**
    * Start editing mode on load.
    */
    'autostart': boolean;
    'getValue': () => Promise<string>;
    /**
    * Image placeholder if there is no image. If not provided, default will be used.
    */
    'placeholder': string;
    'setValue': (data: string) => Promise<void>;
    /**
    * Image source
    */
    'src': string;
    /**
    * Toolbar configuration.  Allowed items: - crop - move - rotate - rotate-left - rotate-right - flip-horizontal - flip-vertical - apply - cancel - separator  Can be provided as array or as a string, items separated with pipe (|)
    */
    'toolbar': string | Array<string>;
  }
  interface RunopencodeProfilePhotoEditorAttributes extends StencilHTMLAttributes {
    /**
    * Start editing mode on load.
    */
    'autostart'?: boolean;
    'onChange'?: (event: CustomEvent) => void;
    /**
    * Image placeholder if there is no image. If not provided, default will be used.
    */
    'placeholder'?: string;
    /**
    * Image source
    */
    'src'?: string;
    /**
    * Toolbar configuration.  Allowed items: - crop - move - rotate - rotate-left - rotate-right - flip-horizontal - flip-vertical - apply - cancel - separator  Can be provided as array or as a string, items separated with pipe (|)
    */
    'toolbar'?: string | Array<string>;
  }

  interface RunopencodeSwitchType {
    'check': () => Promise<void>;
    'disabled': boolean;
    'getValue': () => Promise<boolean>;
    'labelChecked': string | null;
    'labelUnchecked': string | null;
    'readonly': boolean;
    'setValue': (value: boolean) => Promise<void>;
    'toggle': () => Promise<void>;
    'uncheck': () => Promise<void>;
  }
  interface RunopencodeSwitchTypeAttributes extends StencilHTMLAttributes {
    'disabled'?: boolean;
    'labelChecked'?: string | null;
    'labelUnchecked'?: string | null;
    'onChange'?: (event: CustomEvent) => void;
    'readonly'?: boolean;
  }
}

declare global {
  interface StencilElementInterfaces {
    'RunopencodeChoiceType': Components.RunopencodeChoiceType;
    'RunopencodeDateRangeType': Components.RunopencodeDateRangeType;
    'RunopencodeDateType': Components.RunopencodeDateType;
    'RunopencodeProfilePhotoEditor': Components.RunopencodeProfilePhotoEditor;
    'RunopencodeSwitchType': Components.RunopencodeSwitchType;
  }

  interface StencilIntrinsicElements {
    'runopencode-choice-type': Components.RunopencodeChoiceTypeAttributes;
    'runopencode-date-range-type': Components.RunopencodeDateRangeTypeAttributes;
    'runopencode-date-type': Components.RunopencodeDateTypeAttributes;
    'runopencode-profile-photo-editor': Components.RunopencodeProfilePhotoEditorAttributes;
    'runopencode-switch-type': Components.RunopencodeSwitchTypeAttributes;
  }


  interface HTMLRunopencodeChoiceTypeElement extends Components.RunopencodeChoiceType, HTMLStencilElement {}
  var HTMLRunopencodeChoiceTypeElement: {
    prototype: HTMLRunopencodeChoiceTypeElement;
    new (): HTMLRunopencodeChoiceTypeElement;
  };

  interface HTMLRunopencodeDateRangeTypeElement extends Components.RunopencodeDateRangeType, HTMLStencilElement {}
  var HTMLRunopencodeDateRangeTypeElement: {
    prototype: HTMLRunopencodeDateRangeTypeElement;
    new (): HTMLRunopencodeDateRangeTypeElement;
  };

  interface HTMLRunopencodeDateTypeElement extends Components.RunopencodeDateType, HTMLStencilElement {}
  var HTMLRunopencodeDateTypeElement: {
    prototype: HTMLRunopencodeDateTypeElement;
    new (): HTMLRunopencodeDateTypeElement;
  };

  interface HTMLRunopencodeProfilePhotoEditorElement extends Components.RunopencodeProfilePhotoEditor, HTMLStencilElement {}
  var HTMLRunopencodeProfilePhotoEditorElement: {
    prototype: HTMLRunopencodeProfilePhotoEditorElement;
    new (): HTMLRunopencodeProfilePhotoEditorElement;
  };

  interface HTMLRunopencodeSwitchTypeElement extends Components.RunopencodeSwitchType, HTMLStencilElement {}
  var HTMLRunopencodeSwitchTypeElement: {
    prototype: HTMLRunopencodeSwitchTypeElement;
    new (): HTMLRunopencodeSwitchTypeElement;
  };

  interface HTMLElementTagNameMap {
    'runopencode-choice-type': HTMLRunopencodeChoiceTypeElement
    'runopencode-date-range-type': HTMLRunopencodeDateRangeTypeElement
    'runopencode-date-type': HTMLRunopencodeDateTypeElement
    'runopencode-profile-photo-editor': HTMLRunopencodeProfilePhotoEditorElement
    'runopencode-switch-type': HTMLRunopencodeSwitchTypeElement
  }

  interface ElementTagNameMap {
    'runopencode-choice-type': HTMLRunopencodeChoiceTypeElement;
    'runopencode-date-range-type': HTMLRunopencodeDateRangeTypeElement;
    'runopencode-date-type': HTMLRunopencodeDateTypeElement;
    'runopencode-profile-photo-editor': HTMLRunopencodeProfilePhotoEditorElement;
    'runopencode-switch-type': HTMLRunopencodeSwitchTypeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
